# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TEST.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TEST.proto',
  package='ProtoBuf',
  syntax='proto2',
  serialized_pb=_b('\n\nTEST.proto\x12\x08ProtoBuf\"\xf1\x01\n\x04TEST\x12\x13\n\x08goods_id\x18\x01 \x02(\r:\x01\x30\x12\x0e\n\x04name\x18\x02 \x01(\x0c:\x00\x12\x0e\n\x03sex\x18\x03 \x01(\r:\x01\x30\x12\x16\n\x0blevel_limit\x18\x04 \x01(\r:\x01\x30\x12\x19\n\x0e\x63lub_vip_level\x18\x05 \x01(\x05:\x01\x30\x12\x0f\n\x04qb_2\x18\x06 \x01(\x05:\x01\x30\x12\x17\n\x0c\x63onsume_type\x18\x07 \x01(\r:\x01\x30\x12\x14\n\ttime_unit\x18\x08 \x01(\r:\x01\x30\x12\x14\n\tis_online\x18\t \x01(\r:\x01\x30\x12\x12\n\x07\x63\x61n_buy\x18\n \x01(\r:\x01\x30\x12\x17\n\x0c\x63\x61n_recharge\x18\x0b \x01(\r:\x01\x30\"+\n\nTEST_ARRAY\x12\x1d\n\x05items\x18\x01 \x03(\x0b\x32\x0e.ProtoBuf.TEST')
)




_TEST = _descriptor.Descriptor(
  name='TEST',
  full_name='ProtoBuf.TEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goods_id', full_name='ProtoBuf.TEST.goods_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ProtoBuf.TEST.name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='ProtoBuf.TEST.sex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level_limit', full_name='ProtoBuf.TEST.level_limit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='club_vip_level', full_name='ProtoBuf.TEST.club_vip_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qb_2', full_name='ProtoBuf.TEST.qb_2', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consume_type', full_name='ProtoBuf.TEST.consume_type', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_unit', full_name='ProtoBuf.TEST.time_unit', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_online', full_name='ProtoBuf.TEST.is_online', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_buy', full_name='ProtoBuf.TEST.can_buy', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_recharge', full_name='ProtoBuf.TEST.can_recharge', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=266,
)


_TEST_ARRAY = _descriptor.Descriptor(
  name='TEST_ARRAY',
  full_name='ProtoBuf.TEST_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ProtoBuf.TEST_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=311,
)

_TEST_ARRAY.fields_by_name['items'].message_type = _TEST
DESCRIPTOR.message_types_by_name['TEST'] = _TEST
DESCRIPTOR.message_types_by_name['TEST_ARRAY'] = _TEST_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TEST = _reflection.GeneratedProtocolMessageType('TEST', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'TEST_pb2'
  # @@protoc_insertion_point(class_scope:ProtoBuf.TEST)
  ))
_sym_db.RegisterMessage(TEST)

TEST_ARRAY = _reflection.GeneratedProtocolMessageType('TEST_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _TEST_ARRAY,
  __module__ = 'TEST_pb2'
  # @@protoc_insertion_point(class_scope:ProtoBuf.TEST_ARRAY)
  ))
_sym_db.RegisterMessage(TEST_ARRAY)


# @@protoc_insertion_point(module_scope)
