// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: AIAtt.proto

#pragma warning disable CS1591, CS0612, CS3021

[global::ProtoBuf.ProtoContract()]
public partial class AIAtt
{
    [global::ProtoBuf.ProtoMember(1)]
    public int moveInterval { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public float moveRadius { get; set; }

    [global::ProtoBuf.ProtoMember(3)]
    public int attackInterval { get; set; }

    [global::ProtoBuf.ProtoMember(4)]
    public int thinkInterval { get; set; }

    [global::ProtoBuf.ProtoMember(5)]
    public int searchInterval { get; set; }

    [global::ProtoBuf.ProtoMember(6)]
    public float searchRadius { get; set; }

    [global::ProtoBuf.ProtoMember(7)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scriptName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8)]
    public float rotateAngle { get; set; }

}

#pragma warning restore CS1591, CS0612, CS3021
