// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: person.proto

#pragma warning disable CS1591, CS0612, CS3021

[global::ProtoBuf.ProtoContract()]
public partial class SearchRequest
{
    [global::ProtoBuf.ProtoMember(1, Name = @"query")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Query { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"page_number")]
    public int PageNumber { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"result_per_page")]
    public int ResultPerPage { get; set; }

}

#pragma warning restore CS1591, CS0612, CS3021
